[build]
  publish = "dist"
  command = "php build.php"

[build.environment]
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/trainings/"
  to = "/trainings/schedules.json"
  status = 200

[[redirects]]
  from = "/trainings/index.php"
  to = "/trainings/schedules.json"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[context.production]
  publish = "dist"

[context.deploy-preview]
  publish = "dist"

[context.branch-deploy]
  publish = "dist"

