-- MySQL dump 10.13  Distrib 8.4.3, for Linux (aarch64)
--
-- Host: db    Database: db
-- ------------------------------------------------------
-- Server version	8.4.5

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `schedule_templates`
--

LOCK TABLES `schedule_templates` WRITE;
/*!40000 ALTER TABLE `schedule_templates` DISABLE KEYS */;
INSERT INTO `schedule_templates` (`id`, `name`, `start_date`, `end_date`, `is_active`, `created_at`, `updated_at`) VALUES (1,'Schedule 2025-12-22','2025-12-22',NULL,1,'2026-01-24 15:03:22','2026-01-24 15:03:22');
INSERT INTO `schedule_templates` (`id`, `name`, `start_date`, `end_date`, `is_active`, `created_at`, `updated_at`) VALUES (2,'Schedule 2026-01-05','2026-01-05',NULL,1,'2026-01-24 15:03:22','2026-01-24 15:03:22');
INSERT INTO `schedule_templates` (`id`, `name`, `start_date`, `end_date`, `is_active`, `created_at`, `updated_at`) VALUES (3,'Schedule 2026-01-13','2026-01-13',NULL,1,'2026-01-24 15:03:22','2026-01-24 15:03:22');
INSERT INTO `schedule_templates` (`id`, `name`, `start_date`, `end_date`, `is_active`, `created_at`, `updated_at`) VALUES (4,'Schedule 2026-01-17','2026-01-17',NULL,1,'2026-01-24 15:03:22','2026-01-24 15:03:22');
INSERT INTO `schedule_templates` (`id`, `name`, `start_date`, `end_date`, `is_active`, `created_at`, `updated_at`) VALUES (5,'Schedule 2026-01-19','2026-01-19',NULL,1,'2026-01-24 15:03:22','2026-01-24 15:03:22');
/*!40000 ALTER TABLE `schedule_templates` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `schedule_days`
--

LOCK TABLES `schedule_days` WRITE;
/*!40000 ALTER TABLE `schedule_days` DISABLE KEYS */;
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (1,1,1,'mon','MONTAG','Ganzkörper Kraft','dumbbell','text-blue-400','bg-blue-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (2,1,2,'tue','DIENSTAG','Active Office (NEAT)','footprints','text-emerald-400','bg-emerald-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (3,1,3,'wed','MITTWOCH','Ganzkörper Kraft','dumbbell','text-blue-400','bg-blue-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (4,1,4,'thu','DONNERSTAG','Active Recovery','gamepad-2','text-purple-400','bg-purple-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (5,1,5,'fri','FREITAG','Cardio Battle (Boxen)','swords','text-pink-400','bg-pink-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (6,1,6,'sat','SAMSTAG','Nature Walk / Cardio','trees','text-yellow-400','bg-yellow-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (7,1,0,'sun','SONNTAG','Rest & Recovery','coffee','text-slate-300','bg-slate-700/50');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (8,2,1,'mon','MONTAG','Ganzkörper Kraft (Fokus Rücken & Bizeps)','dumbbell','text-blue-400','bg-blue-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (9,2,2,'tue','DIENSTAG','Active Office (NEAT)','footprints','text-emerald-400','bg-emerald-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (10,2,3,'wed','MITTWOCH','Ganzkörper Kraft (Volume)','dumbbell','text-blue-400','bg-blue-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (11,2,4,'thu','DONNERSTAG','Active Recovery','gamepad-2','text-purple-400','bg-purple-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (12,2,5,'fri','FREITAG','Cardio & Core','swords','text-pink-400','bg-pink-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (13,2,6,'sat','SAMSTAG','Nature Walk / Cardio','trees','text-yellow-400','bg-yellow-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (14,2,0,'sun','SONNTAG','Rest & Recovery','coffee','text-slate-300','bg-slate-700/50');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (15,3,1,'mon','MONTAG','Ganzkörper Kraft & Support','dumbbell','text-blue-400','bg-blue-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (16,3,2,'tue','DIENSTAG','Active Office (NEAT)','footprints','text-emerald-400','bg-emerald-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (17,3,3,'wed','MITTWOCH','Ganzkörper Kraft (Volume)','dumbbell','text-blue-400','bg-blue-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (18,3,4,'thu','DONNERSTAG','Active Recovery','gamepad-2','text-purple-400','bg-purple-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (19,3,5,'fri','FREITAG','Cardio & Core','swords','text-pink-400','bg-pink-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (20,3,6,'sat','SAMSTAG','Nature Walk / Cardio','trees','text-yellow-400','bg-yellow-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (21,3,0,'sun','SONNTAG','Rest & Recovery','coffee','text-slate-300','bg-slate-700/50');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (22,4,1,'mon','MONTAG','Ganzkörper Kraft & Balance','dumbbell','text-blue-400','bg-blue-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (23,4,2,'tue','DIENSTAG','Active Office (NEAT)','footprints','text-emerald-400','bg-emerald-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (24,4,3,'wed','MITTWOCH','Kraft & Core Focus','dumbbell','text-blue-400','bg-blue-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (25,4,4,'thu','DONNERSTAG','Active Recovery','gamepad-2','text-purple-400','bg-purple-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (26,4,5,'fri','FREITAG','Cardio & Core','swords','text-pink-400','bg-pink-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (27,4,6,'sat','SAMSTAG','Nature Walk / Cardio','trees','text-yellow-400','bg-yellow-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (28,4,0,'sun','SONNTAG','Rest & Recovery','coffee','text-slate-300','bg-slate-700/50');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (29,5,1,'mon','MONTAG','Ganzkörper Kraft & Balance','dumbbell','text-blue-400','bg-blue-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (30,5,2,'tue','DIENSTAG','Active Office (NEAT)','footprints','text-emerald-400','bg-emerald-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (31,5,3,'wed','MITTWOCH','Kraft & Core Focus','dumbbell','text-blue-400','bg-blue-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (32,5,4,'thu','DONNERSTAG','Active Recovery','gamepad-2','text-purple-400','bg-purple-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (33,5,5,'fri','FREITAG','Cardio & Core','swords','text-pink-400','bg-pink-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (34,5,6,'sat','SAMSTAG','Nature Walk / Cardio','trees','text-yellow-400','bg-yellow-500/10');
INSERT INTO `schedule_days` (`id`, `template_id`, `day_index`, `day_id`, `name`, `theme`, `icon`, `color_class`, `bg_class`) VALUES (35,5,0,'sun','SONNTAG','Rest & Recovery','coffee','text-slate-300','bg-slate-700/50');
/*!40000 ALTER TABLE `schedule_days` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `schedule_exercises`
--

LOCK TABLES `schedule_exercises` WRITE;
/*!40000 ALTER TABLE `schedule_exercises` DISABLE KEYS */;
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (1,1,'warmup_row',0,'warmup','Rudern','Aufwärmen',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}, {\"l\": \"7 Min\", \"s\": 420}, {\"l\": \"10 Min\", \"s\": 600}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (2,1,'ex_beinstrecken',1,'main','Beinstrecken','2 x 15 Wdh','2','STUFE',NULL,'{\"reps\": 15, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (3,1,'ex_latziehen',2,'main','Latziehen','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (4,1,'ex_brustpresse',3,'main','Brustpresse','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (5,1,'ex_butterfly',4,'main','Butterfly','2 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (6,1,'cool_stretch',5,'cool','Cooldown','Stretching',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}, {\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (7,2,'warmup_mob',0,'warmup','Joint Mobility','Beine ausschütteln',NULL,NULL,'[{\"l\": \"1 Min\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (8,2,'ex_walking',1,'main','Walkingpad','Schritte sammeln',NULL,NULL,'[{\"l\": \"45 Min\", \"s\": 2700}, {\"l\": \"60 Min\", \"s\": 3600}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (9,2,'cool_hip',2,'cool','Hüftbeuger Dehnen','Halten',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (10,3,'warmup_blaze',0,'warmup','Blazepods','Reaction Drill',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (11,3,'ex_beinstrecken',1,'main','Beinstrecken','2 x 15 Wdh','2','STUFE',NULL,'{\"reps\": 15, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (12,3,'ex_latziehen',2,'main','Latziehen','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (13,3,'ex_brustpresse',3,'main','Brustpresse','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (14,3,'ex_butterfly',4,'main','Butterfly','2 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (15,3,'cool_foam',5,'cool','Cooldown','Foam Rolling',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (16,4,'warmup_arms',0,'warmup','Armkreisen','Schultern lockern',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (17,4,'m_alt_group_thu',1,'alternatives','Beat Saber (VR) / Yoga',NULL,NULL,NULL,'[{\"desc\": \"Expert Level\", \"title\": \"Beat Saber (VR)\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}]}, {\"desc\": \"Rücken Fokus\", \"title\": \"Yoga\", \"timers\": [{\"l\": \"20 Min\", \"s\": 1200}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (18,4,'cool_child',2,'cool','Child\'s Pose','Entspannung',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (19,5,'warmup_shadow',0,'warmup','Schattenboxen','Locker bewegen',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (20,5,'ex_boxen',1,'main','Boxsack & Pods','5 Runden',NULL,NULL,'[{\"l\": \"20 Min\", \"s\": 1200}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (21,5,'cool_upper',2,'cool','Oberkörper Stretch','Dehnen',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (22,6,'warmup_joints',0,'warmup','Gelenke kreisen','Vorbereitung',NULL,NULL,'[{\"l\": \"1 Min\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (23,6,'m_alt_group_sat',1,'alternatives','Nature Walk / Indoor Cardio',NULL,NULL,NULL,'[{\"desc\": \"Draußen (Gut Wetter)\", \"title\": \"Nature Walk\", \"timers\": [{\"l\": \"60 Min\", \"s\": 3600}]}, {\"desc\": \"Laufband / Rad\", \"title\": \"Indoor Cardio\", \"timers\": [{\"l\": \"45 Min\", \"s\": 2700}, {\"l\": \"60 Min\", \"s\": 3600}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (24,6,'cool_calves',2,'cool','Waden dehnen','Wichtig!',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (25,7,'warmup_mob_sun',0,'warmup','Mobilisation','Schulterkreisen',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (26,7,'ex_rest_group_sun',1,'alternatives','Spaziergang / Walkingpad',NULL,NULL,NULL,'[{\"desc\": \"Draußen (Frische Luft)\", \"title\": \"Spaziergang\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}, {\"l\": \"45 Min\", \"s\": 2700}]}, {\"desc\": \"Indoor (Light)\", \"title\": \"Walkingpad\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (27,7,'cool_mental',2,'cool','Mental Reset','Wochenplanung',NULL,NULL,'[{\"l\": \"10 Min\", \"s\": 600}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (28,8,'warmup_row',0,'warmup','Rudern','Aufwärmen',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}, {\"l\": \"7 Min\", \"s\": 420}, {\"l\": \"10 Min\", \"s\": 600}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (29,8,'ex_beinstrecken',1,'main','Beinstrecken','3 x 15 Wdh','2','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (30,8,'ex_latziehen',2,'main','Latziehen','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (31,8,'ex_rudern',3,'main','Rudern sitzend','3 x 12 Wdh (Neu: Rückendichte)','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (32,8,'ex_brustpresse',4,'main','Brustpresse','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (33,8,'ex_butterfly',5,'main','Butterfly','2 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (34,8,'ex_bizeps',6,'main','Bizeps Curls','3 x 12 Wdh (Neu: Arme)','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (35,8,'cool_stretch',7,'cool','Cooldown','Stretching',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}, {\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (36,9,'warmup_mob',0,'warmup','Joint Mobility','Beine ausschütteln',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (37,9,'ex_walking',1,'main','Walkingpad','Schritte sammeln (Ziel erhöht)',NULL,NULL,'[{\"l\": \"50 Min\", \"s\": 3000}, {\"l\": \"70 Min\", \"s\": 4200}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (38,9,'cool_hip',2,'cool','Hüftbeuger Dehnen','Halten',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (39,10,'warmup_blaze',0,'warmup','Blazepods','Reaction Drill',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (40,10,'ex_beinstrecken',1,'main','Beinstrecken','3 x 15 Wdh','2','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (41,10,'ex_latziehen',2,'main','Latziehen','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (42,10,'ex_rudern',3,'main','Rudern sitzend','3 x 12 Wdh (Neu)','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (43,10,'ex_brustpresse',4,'main','Brustpresse','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (44,10,'ex_butterfly',5,'main','Butterfly','2 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (45,10,'ex_butter_rev',6,'main','Butterfly Reverse','2 x 12 Wdh (Neu: Hintere Schulter)','2','KG',NULL,'{\"reps\": 12, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (46,10,'ex_bizeps',7,'main','Bizeps Curls','3 x 12 Wdh (Neu)','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (47,10,'cool_foam',8,'cool','Cooldown','Foam Rolling',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (48,11,'warmup_arms',0,'warmup','Armkreisen','Schultern lockern',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (49,11,'m_alt_group_thu',1,'alternatives','Beat Saber (VR) / Yoga',NULL,NULL,NULL,'[{\"desc\": \"Expert Level - Dauer erhöht\", \"title\": \"Beat Saber (VR)\", \"timers\": [{\"l\": \"40 Min\", \"s\": 2400}]}, {\"desc\": \"Rücken Fokus - Dauer erhöht\", \"title\": \"Yoga\", \"timers\": [{\"l\": \"25 Min\", \"s\": 1500}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (50,11,'cool_child',2,'cool','Child\'s Pose','Entspannung',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (51,12,'warmup_shadow',0,'warmup','Schattenboxen','Locker bewegen',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (52,12,'ex_boxen',1,'main','Boxsack & Pods','5 Runden',NULL,NULL,'[{\"l\": \"20 Min\", \"s\": 1200}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (53,12,'ex_plank',2,'main','Plank (Unterarmstütz)','Neu: Core Stabilität',NULL,NULL,'[{\"l\": \"30s\", \"s\": 30}, {\"l\": \"45s\", \"s\": 45}, {\"l\": \"60s\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (54,12,'cool_upper',3,'cool','Oberkörper Stretch','Dehnen',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (55,13,'warmup_joints',0,'warmup','Gelenke kreisen','Vorbereitung',NULL,NULL,'[{\"l\": \"1 Min\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (56,13,'m_alt_group_sat',1,'alternatives','Nature Walk / Indoor Cardio',NULL,NULL,NULL,'[{\"desc\": \"Draußen (Ausdauer)\", \"title\": \"Nature Walk\", \"timers\": [{\"l\": \"70 Min\", \"s\": 4200}, {\"l\": \"90 Min\", \"s\": 5400}]}, {\"desc\": \"Laufband / Rad\", \"title\": \"Indoor Cardio\", \"timers\": [{\"l\": \"50 Min\", \"s\": 3000}, {\"l\": \"60 Min\", \"s\": 3600}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (57,13,'cool_calves',2,'cool','Waden dehnen','Wichtig!',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (58,14,'warmup_mob_sun',0,'warmup','Mobilisation','Schulterkreisen',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (59,14,'ex_rest_group_sun',1,'alternatives','Spaziergang / Walkingpad',NULL,NULL,NULL,'[{\"desc\": \"Draußen (Frische Luft)\", \"title\": \"Spaziergang\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}, {\"l\": \"45 Min\", \"s\": 2700}]}, {\"desc\": \"Indoor (Light)\", \"title\": \"Walkingpad\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (60,14,'cool_mental',2,'cool','Mental Reset','Wochenplanung',NULL,NULL,'[{\"l\": \"10 Min\", \"s\": 600}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (61,15,'warmup_row',0,'warmup','Rudern','Aufwärmen',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}, {\"l\": \"7 Min\", \"s\": 420}, {\"l\": \"10 Min\", \"s\": 600}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (62,15,'ex_adduktion',1,'main','Bein-Adduktion','Kabelzug/Schlaufe: Bein nach innen ziehen. Hilft beim Rudern!','1','STUFE',NULL,'{\"reps\": 15, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (63,15,'ex_beinstrecken',2,'main','Beinstrecken','3 x 15 Wdh','2','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (64,15,'ex_latziehen',3,'main','Latziehen','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (65,15,'ex_rudern',4,'main','Rudern sitzend','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2300}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (66,15,'ex_brustpresse',5,'main','Brustpresse','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (67,15,'ex_butterfly',6,'main','Butterfly','2 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (68,15,'ex_bizeps',7,'main','Bizeps Curls','3 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (69,15,'cool_stretch',8,'cool','Cooldown','Stretching',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}, {\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (70,16,'warmup_mob',0,'warmup','Joint Mobility','Beine ausschütteln',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (71,16,'ex_walking',1,'main','Walkingpad','Schritte sammeln',NULL,NULL,'[{\"l\": \"50 Min\", \"s\": 3000}, {\"l\": \"70 Min\", \"s\": 4200}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (72,16,'cool_hip',2,'cool','Hüftbeuger Dehnen','Halten',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (73,17,'warmup_blaze',0,'warmup','Blazepods','Reaction Drill',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (74,17,'ex_adduktion',1,'main','Bein-Adduktion','Kabelzug/Schlaufe: Bein nach innen ziehen. Hilft beim Rudern!','1','STUFE',NULL,'{\"reps\": 15, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (75,17,'ex_beinstrecken',2,'main','Beinstrecken','3 x 15 Wdh','2','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (76,17,'ex_latziehen',3,'main','Latziehen','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (77,17,'ex_rudern',4,'main','Rudern sitzend','3 x 12 Wdh (Neu)','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (78,17,'ex_brustpresse',5,'main','Brustpresse','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (79,17,'ex_butterfly',6,'main','Butterfly','2 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (80,17,'ex_butter_rev',7,'main','Butterfly Reverse','2 x 12 Wdh','2','KG',NULL,'{\"reps\": 12, \"sets\": 2, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (81,17,'ex_bizeps',8,'main','Bizeps Curls','3 x 12 Wdh (Neu)','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (82,17,'cool_foam',9,'cool','Cooldown','Foam Rolling',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (83,18,'warmup_arms',0,'warmup','Armkreisen','Schultern lockern',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (84,18,'m_alt_group_thu',1,'alternatives','Beat Saber (VR) / Yoga',NULL,NULL,NULL,'[{\"desc\": \"Expert Level - Dauer erhöht\", \"title\": \"Beat Saber (VR)\", \"timers\": [{\"l\": \"40 Min\", \"s\": 2400}]}, {\"desc\": \"Rücken Fokus - Dauer erhöht\", \"title\": \"Yoga\", \"timers\": [{\"l\": \"25 Min\", \"s\": 1500}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (85,18,'cool_child',2,'cool','Child\'s Pose','Entspannung',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (86,19,'warmup_shadow',0,'warmup','Schattenboxen','Locker bewegen',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (87,19,'ex_boxen',1,'main','Boxsack & Pods','5 Runden',NULL,NULL,'[{\"l\": \"20 Min\", \"s\": 1200}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (88,19,'ex_incline_plank',2,'main','Incline Plank (Bank)','Hände auf Hantelbank, Körper gerade. Leichter als Boden!',NULL,NULL,'[{\"l\": \"30s\", \"s\": 30}, {\"l\": \"45s\", \"s\": 45}, {\"l\": \"60s\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (89,19,'ex_bank_crunches',3,'main','Crunches (Bank-Ablage)','Rücken auf Matte, Waden 90° auf Bank ablegen. Kopf anheben.',NULL,NULL,NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (90,19,'cool_upper',4,'cool','Oberkörper Stretch','Dehnen',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (91,20,'warmup_joints',0,'warmup','Gelenke kreisen','Vorbereitung',NULL,NULL,'[{\"l\": \"1 Min\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (92,20,'m_alt_group_sat',1,'alternatives','Nature Walk / Indoor Cardio',NULL,NULL,NULL,'[{\"desc\": \"Draußen (Ausdauer)\", \"title\": \"Nature Walk\", \"timers\": [{\"l\": \"70 Min\", \"s\": 4200}, {\"l\": \"90 Min\", \"s\": 5400}]}, {\"desc\": \"Laufband / Rad\", \"title\": \"Indoor Cardio\", \"timers\": [{\"l\": \"50 Min\", \"s\": 3000}, {\"l\": \"60 Min\", \"s\": 3600}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (93,20,'cool_calves',2,'cool','Waden dehnen','Wichtig!',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (94,21,'warmup_mob_sun',0,'warmup','Mobilisation','Schulterkreisen',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (95,21,'ex_rest_group_sun',1,'alternatives','Spaziergang / Walkingpad',NULL,NULL,NULL,'[{\"desc\": \"Draußen (Frische Luft)\", \"title\": \"Spaziergang\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}, {\"l\": \"45 Min\", \"s\": 2700}]}, {\"desc\": \"Indoor (Light)\", \"title\": \"Walkingpad\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (96,21,'cool_mental',2,'cool','Mental Reset','Wochenplanung',NULL,NULL,'[{\"l\": \"10 Min\", \"s\": 600}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (97,22,'warmup_row',0,'warmup','Rudern','Aufwärmen',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}, {\"l\": \"7 Min\", \"s\": 420}, {\"l\": \"10 Min\", \"s\": 600}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (98,22,'ex_adduktion',1,'main','Bein-Adduktion','4 Sätze (2x Links, 2x Rechts - Wechsel als Pause).','1','STUFE',NULL,'{\"reps\": 15, \"sets\": 4, \"restSeconds\": 30, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (99,22,'ex_beinstrecken',2,'main','Beinstrecken','3 x 15 Wdh (Tempo angepasst: 2.5s)','2','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (100,22,'ex_latziehen',3,'main','Latziehen','3 x 15 Wdh (Volumen erhöht)','3','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (101,22,'ex_rudern',4,'main','Rudern sitzend','3 x 15 Wdh (Volumen erhöht)','3','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2300}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (102,22,'ex_brustpresse',5,'main','Brustpresse','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (103,22,'ex_butterfly',6,'main','Butterfly','3 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (104,22,'ex_butter_rev',7,'main','Butterfly Reverse','3 x 12 Wdh (Hintere Schulter - Neu am Mo)','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (105,22,'ex_trizeps_seil',8,'main','Trizeps Drücken (Seil)','Neu: Arme isoliert. Ellbogen fixieren!','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (106,22,'ex_bizeps',9,'main','Bizeps Curls','3 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (107,22,'ex_beinbeugen_kabel',10,'main','Beinbeugen stehend (Kabel)','NEU: 4 Sätze (2x Links, 2x Rechts). Ferse zum Po ziehen.','1','STUFE',NULL,'{\"reps\": 12, \"sets\": 4, \"restSeconds\": 30, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (108,22,'cool_stretch',11,'cool','Cooldown','Stretching',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}, {\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (109,23,'warmup_mob',0,'warmup','Joint Mobility','Beine ausschütteln',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (110,23,'ex_walking',1,'main','Walkingpad','Schritte sammeln',NULL,NULL,'[{\"l\": \"50 Min\", \"s\": 3000}, {\"l\": \"70 Min\", \"s\": 4200}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (111,23,'cool_hip',2,'cool','Hüftbeuger Dehnen','Halten',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (112,24,'warmup_blaze',0,'warmup','Blazepods','Reaction Drill',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (113,24,'ex_adduktion',1,'main','Bein-Adduktion','4 Sätze (2x L, 2x R - Wechsel als Pause).','1','STUFE',NULL,'{\"reps\": 15, \"sets\": 4, \"restSeconds\": 30, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (114,24,'ex_beinstrecken',2,'main','Beinstrecken','3 x 15 Wdh','2','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (115,24,'ex_latziehen',3,'main','Latziehen','3 x 15 Wdh (Volumen erhöht)','3','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (116,24,'ex_rudern',4,'main','Rudern sitzend','3 x 15 Wdh (Volumen erhöht)','3','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2300}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (117,24,'ex_brustpresse',5,'main','Brustpresse','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (118,24,'ex_butterfly',6,'main','Butterfly','3 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (119,24,'ex_trizeps_seil',7,'main','Trizeps Drücken (Seil)','Mit Seil am Kabelzug.','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (120,24,'ex_crunches_bank_90',8,'main','Crunches (90° Ablage)','Rücken auf Matte, Waden 90° auf Bank. Bauch isolieren.','0','KG',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (121,24,'ex_pull_through',9,'main','Cable Pull-Throughs','NEU: Mit Seil durch die Beine. Hüfte vorstrecken! Gluteus-Fokus.','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (122,24,'cool_foam_bws',10,'cool','Foam: Oberer Rücken','Rolle quer. Hände hinter Kopf.',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (123,24,'cool_foam_quads',11,'cool','Foam: Oberschenkel','Bauchlage (Plank) auf Rolle. Vorderseite langsam abfahren.',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (124,24,'cool_foam_glutes',12,'cool','Foam: Gesäß','Auf Rolle sitzen, 4er-Form (Bein überschlagen).',NULL,NULL,'[{\"l\": \"1 Min\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (125,25,'warmup_arms',0,'warmup','Armkreisen','Schultern lockern',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (126,25,'m_alt_group_thu',1,'alternatives','Beat Saber (VR) / Yoga',NULL,NULL,NULL,'[{\"desc\": \"Expert Level\", \"title\": \"Beat Saber (VR)\", \"timers\": [{\"l\": \"40 Min\", \"s\": 2400}]}, {\"desc\": \"Rücken Fokus\", \"title\": \"Yoga\", \"timers\": [{\"l\": \"25 Min\", \"s\": 1500}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (127,25,'cool_child',2,'cool','Child\'s Pose','Entspannung',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (128,26,'warmup_shadow',0,'warmup','Schattenboxen','Locker bewegen',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (129,26,'ex_boxen',1,'main','Boxsack & Pods','5 Runden',NULL,NULL,'[{\"l\": \"20 Min\", \"s\": 1200}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (130,26,'ex_incline_plank',2,'main','Incline Plank (Bank)','Hände auf Bank, Körper gerade. Winkel dokumentieren!','3','STUFE','[{\"l\": \"30s\", \"s\": 30}, {\"l\": \"45s\", \"s\": 45}, {\"l\": \"60s\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (131,26,'ex_crunches_bank_90_fri',3,'main','Crunches (90° Ablage)','Wie Mi: Rücken auf Matte, Beine auf Bank.','0','KG',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (132,26,'ex_decline_max',4,'main','Decline Crunches (MAX)','Bank negativ. Beine fixieren. Ein Satz so viele wie möglich! Hausaufgabe: Mitzählen!','0','REPS',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (133,26,'ex_deadbug',5,'main','Dead Bug (Toter Käfer)','NEU: Rücken flach am Boden. Arm/Bein langsam senken. Anti-Hohlkreuz!','0','KG',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 4000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (134,26,'cool_upper',6,'cool','Oberkörper Stretch','Dehnen',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (135,27,'warmup_joints',0,'warmup','Gelenke kreisen','Vorbereitung',NULL,NULL,'[{\"l\": \"1 Min\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (136,27,'m_alt_group_sat',1,'alternatives','Nature Walk / Indoor Cardio',NULL,NULL,NULL,'[{\"desc\": \"Draußen (Ausdauer)\", \"title\": \"Nature Walk\", \"timers\": [{\"l\": \"70 Min\", \"s\": 4200}, {\"l\": \"90 Min\", \"s\": 5400}]}, {\"desc\": \"Laufband / Rad\", \"title\": \"Indoor Cardio\", \"timers\": [{\"l\": \"50 Min\", \"s\": 3000}, {\"l\": \"60 Min\", \"s\": 3600}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (137,27,'cool_calves',2,'cool','Waden dehnen','Wichtig!',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (138,28,'warmup_mob_sun',0,'warmup','Mobilisation','Schulterkreisen',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (139,28,'ex_rest_group_sun',1,'alternatives','Spaziergang / Walkingpad',NULL,NULL,NULL,'[{\"desc\": \"Draußen (Frische Luft)\", \"title\": \"Spaziergang\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}, {\"l\": \"45 Min\", \"s\": 2700}]}, {\"desc\": \"Indoor (Light)\", \"title\": \"Walkingpad\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (140,28,'cool_mental',2,'cool','Mental Reset','Wochenplanung',NULL,NULL,'[{\"l\": \"10 Min\", \"s\": 600}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (141,29,'warmup_row',0,'warmup','Rudern','Aufwärmen',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}, {\"l\": \"7 Min\", \"s\": 420}, {\"l\": \"10 Min\", \"s\": 600}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (142,29,'ex_adduktion',1,'main','Bein-Adduktion','4 Sätze (2x Links, 2x Rechts - Wechsel als Pause).','1','STUFE',NULL,'{\"reps\": 15, \"sets\": 4, \"bilateral\": true, \"restSeconds\": 30, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (143,29,'ex_beinstrecken',2,'main','Beinstrecken','3 x 15 Wdh (Tempo angepasst: 2.5s)','2','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (144,29,'ex_latziehen',3,'main','Latziehen','3 x 15 Wdh (Volumen erhöht)','3','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (145,29,'ex_rudern',4,'main','Rudern sitzend','3 x 15 Wdh (Volumen erhöht)','3','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2300}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (146,29,'ex_brustpresse',5,'main','Brustpresse','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (147,29,'ex_butterfly',6,'main','Butterfly','3 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (148,29,'ex_butter_rev',7,'main','Butterfly Reverse','3 x 12 Wdh (Hintere Schulter - Neu am Mo)','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (149,29,'ex_trizeps_seil',8,'main','Trizeps Drücken (Seil)','Neu: Arme isoliert. Ellbogen fixieren!','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (150,29,'ex_bizeps',9,'main','Bizeps Curls','3 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (151,29,'ex_beinbeugen_kabel',10,'main','Beinbeugen stehend (Kabel)','NEU: 4 Sätze (2x Links, 2x Rechts). Ferse zum Po ziehen.','1','STUFE',NULL,'{\"reps\": 12, \"sets\": 4, \"bilateral\": true, \"restSeconds\": 30, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (152,29,'cool_stretch',11,'cool','Cooldown','Stretching',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}, {\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (153,30,'warmup_mob',0,'warmup','Joint Mobility','Beine ausschütteln',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (154,30,'ex_walking',1,'main','Walkingpad','Schritte sammeln',NULL,NULL,'[{\"l\": \"50 Min\", \"s\": 3000}, {\"l\": \"70 Min\", \"s\": 4200}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (155,30,'cool_hip',2,'cool','Hüftbeuger Dehnen','Halten',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (156,31,'warmup_blaze',0,'warmup','Blazepods','Reaction Drill',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (157,31,'ex_adduktion',1,'main','Bein-Adduktion','4 Sätze (2x L, 2x R - Wechsel als Pause).','1','STUFE',NULL,'{\"reps\": 15, \"sets\": 4, \"bilateral\": true, \"restSeconds\": 30, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (158,31,'ex_beinstrecken',2,'main','Beinstrecken','3 x 15 Wdh','2','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (159,31,'ex_latziehen',3,'main','Latziehen','3 x 15 Wdh (Volumen erhöht)','3','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2750}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (160,31,'ex_rudern',4,'main','Rudern sitzend','3 x 15 Wdh (Volumen erhöht)','3','STUFE',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2300}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (161,31,'ex_brustpresse',5,'main','Brustpresse','3 x 12 Wdh','3','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (162,31,'ex_butterfly',6,'main','Butterfly','3 x 12 Wdh','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (163,31,'ex_trizeps_seil',7,'main','Trizeps Drücken (Seil)','Mit Seil am Kabelzug.','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2500}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (164,31,'ex_crunches_bank_90',8,'main','Crunches (90° Ablage)','Rücken auf Matte, Waden 90° auf Bank. Bauch isolieren.','0','KG',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (165,31,'ex_pull_through',9,'main','Cable Pull-Throughs','NEU: Mit Seil durch die Beine. Hüfte vorstrecken! Gluteus-Fokus.','2','STUFE',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 3000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (166,31,'cool_foam_bws',10,'cool','Foam: Oberer Rücken','Rolle quer. Hände hinter Kopf.</div><div class=\'flex gap-2 mt-2 flex-wrap\'><a href=\'https://www.youtube.com/watch?v=hWHv-V5uNo4\' target=\'_blank\' class=\'system-timer-chip\' style=\'background-color: #991b1b; color: #fef2f2; border: 1px solid #7f1d1d;\'>▶️ Tutorial</a>',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (167,31,'cool_foam_quads',11,'cool','Foam: Oberschenkel','Bauchlage (Plank) auf Rolle. Vorderseite langsam abfahren.</div><div class=\'flex gap-2 mt-2 flex-wrap\'><a href=\'https://www.youtube.com/watch?v=J_-r4odY47M\' target=\'_blank\' class=\'system-timer-chip\' style=\'background-color: #991b1b; color: #fef2f2; border: 1px solid #7f1d1d;\'>▶️ Tutorial</a>',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (168,31,'cool_foam_glutes',12,'cool','Foam: Gesäß','Auf Rolle sitzen, 4er-Form (Bein überschlagen).</div><div class=\'flex gap-2 mt-2 flex-wrap\'><a href=\'https://www.youtube.com/watch?v=GSu4qZaJDgo\' target=\'_blank\' class=\'system-timer-chip\' style=\'background-color: #991b1b; color: #fef2f2; border: 1px solid #7f1d1d;\'>▶️ Tutorial</a>',NULL,NULL,'[{\"l\": \"1 Min\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (169,32,'warmup_arms',0,'warmup','Armkreisen','Schultern lockern',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (170,32,'m_alt_group_thu',1,'alternatives','Beat Saber (VR) / Yoga',NULL,NULL,NULL,'[{\"desc\": \"Expert Level\", \"title\": \"Beat Saber (VR)\", \"timers\": [{\"l\": \"40 Min\", \"s\": 2400}]}, {\"desc\": \"Rücken Fokus\", \"title\": \"Yoga\", \"timers\": [{\"l\": \"25 Min\", \"s\": 1500}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (171,32,'cool_child',2,'cool','Child\'s Pose','Entspannung',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (172,33,'warmup_shadow',0,'warmup','Schattenboxen','Locker bewegen',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (173,33,'ex_boxen',1,'main','Boxsack & Pods','5 Runden',NULL,NULL,'[{\"l\": \"20 Min\", \"s\": 1200}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (174,33,'ex_incline_plank',2,'main','Incline Plank (Bank)','Hände auf Bank, Körper gerade. Winkel dokumentieren!','3','STUFE','[{\"l\": \"30s\", \"s\": 30}, {\"l\": \"45s\", \"s\": 45}, {\"l\": \"60s\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (175,33,'ex_crunches_bank_90_fri',3,'main','Crunches (90° Ablage)','Wie Mi: Rücken auf Matte, Beine auf Bank.','0','KG',NULL,'{\"reps\": 15, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 2000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (176,33,'ex_decline_max',4,'main','Decline Crunches (MAX)','Bank negativ. Beine fixieren. Ein Satz so viele wie möglich! Hausaufgabe: Mitzählen!','0','REPS',NULL,NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (177,33,'ex_deadbug',5,'main','Dead Bug (Toter Käfer)','NEU: Rücken flach am Boden. Arm/Bein langsam senken. Anti-Hohlkreuz!','0','KG',NULL,'{\"reps\": 12, \"sets\": 3, \"restSeconds\": 60, \"delayMilliseconds\": 4000}',NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (178,33,'cool_upper',6,'cool','Oberkörper Stretch','Dehnen',NULL,NULL,'[{\"l\": \"5 Min\", \"s\": 300}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (179,34,'warmup_joints',0,'warmup','Gelenke kreisen','Vorbereitung',NULL,NULL,'[{\"l\": \"1 Min\", \"s\": 60}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (180,34,'m_alt_group_sat',1,'alternatives','Nature Walk / Indoor Cardio',NULL,NULL,NULL,'[{\"desc\": \"Draußen (Ausdauer)\", \"title\": \"Nature Walk\", \"timers\": [{\"l\": \"70 Min\", \"s\": 4200}, {\"l\": \"90 Min\", \"s\": 5400}]}, {\"desc\": \"Laufband / Rad\", \"title\": \"Indoor Cardio\", \"timers\": [{\"l\": \"50 Min\", \"s\": 3000}, {\"l\": \"60 Min\", \"s\": 3600}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (181,34,'cool_calves',2,'cool','Waden dehnen','Wichtig!',NULL,NULL,'[{\"l\": \"2 Min\", \"s\": 120}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (182,35,'warmup_mob_sun',0,'warmup','Mobilisation','Schulterkreisen',NULL,NULL,'[{\"l\": \"3 Min\", \"s\": 180}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (183,35,'ex_rest_group_sun',1,'alternatives','Spaziergang / Walkingpad',NULL,NULL,NULL,'[{\"desc\": \"Draußen (Frische Luft)\", \"title\": \"Spaziergang\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}, {\"l\": \"45 Min\", \"s\": 2700}]}, {\"desc\": \"Indoor (Light)\", \"title\": \"Walkingpad\", \"timers\": [{\"l\": \"30 Min\", \"s\": 1800}]}]',NULL,NULL,NULL,NULL);
INSERT INTO `schedule_exercises` (`id`, `day_id`, `exercise_id`, `sort_order`, `type`, `title`, `description`, `weight`, `default_unit`, `timers`, `rep_counter`, `custom_label`, `date_condition`, `date_description`) VALUES (184,35,'cool_mental',2,'cool','Mental Reset','Wochenplanung',NULL,NULL,'[{\"l\": \"10 Min\", \"s\": 600}]',NULL,NULL,NULL,NULL);
/*!40000 ALTER TABLE `schedule_exercises` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `date_overrides`
--

LOCK TABLES `date_overrides` WRITE;
/*!40000 ALTER TABLE `date_overrides` DISABLE KEYS */;
/*!40000 ALTER TABLE `date_overrides` ENABLE KEYS */;
UNLOCK TABLES;

--
-- Dumping data for table `schedule_audit`
--

LOCK TABLES `schedule_audit` WRITE;
/*!40000 ALTER TABLE `schedule_audit` DISABLE KEYS */;
/*!40000 ALTER TABLE `schedule_audit` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-01-24 16:22:01
